### ISSUE TITLE
How to calculate intra-fid score?

### ISSUE THREAD

**Issue by youjiangxu** [takuhirok/rGAN#2]
hi @takuhirok ,
      Nice work!

      Can you tell me how to calculate the intra-fid score on the Cifar-10 dataset? How many clean images in the test dataset (or generated images by GAN) are used for calculating this score?

Best,
Youjiang Xu

**Comment by takuhirokaneko** [comment]
The evaluation details are provided in Appendix D.2.2 in https://arxiv.org/pdf/1811.11165.pdf.

We computed Intra FID between the 5k samples generated by G and all the samples in the training set belonging to the class of concern.

**Comment by takuhirok** [comment]
The evaluation details are provided in Appendix D.2.2 in https://arxiv.org/pdf/1811.11165.pdf.

We computed Intra FID between the 5k samples generated by G and all the samples in the training set belonging to the class of concern.

**Comment by youjiangxu** [comment]
Thank you very much!
